"""WebSocket protocol package initialization."""

from .frontend import (
    AudioMessage,
    ControlMessage,
    ErrorMessage,
    FrontendMessage,
    HandoffStatusMessage,
    MessageType,
    PhaseChangedMessage,
    SessionEndMessage,
    SlotInfo,
    SlotsSnapshotMessage,
    ToolCallMessage,
    TranscriptMessage,
    parse_frontend_message,
)
from .handoff import (
    HandoffAckMessage,
    HandoffAudioMessage,
    HandoffControlMessage,
    HandoffErrorMessage,
    HandoffInitMessage,
    HandoffMessage,
    HandoffMessageType,
    HandoffPhaseChangedMessage,
    HandoffSessionEndMessage,
    HandoffSlotInfo,
    HandoffSlotsSnapshotMessage,
    HandoffToolCallMessage,
    HandoffTranscriptMessage,
    parse_handoff_message,
)

__all__ = [
    # Frontend protocol
    "MessageType",
    "AudioMessage",
    "ControlMessage",
    "TranscriptMessage",
    "PhaseChangedMessage",
    "SlotsSnapshotMessage",
    "SlotInfo",
    "ToolCallMessage",
    "HandoffStatusMessage",
    "SessionEndMessage",
    "ErrorMessage",
    "FrontendMessage",
    "parse_frontend_message",
    # Handoff protocol
    "HandoffMessageType",
    "HandoffInitMessage",
    "HandoffAckMessage",
    "HandoffAudioMessage",
    "HandoffControlMessage",
    "HandoffTranscriptMessage",
    "HandoffPhaseChangedMessage",
    "HandoffSlotsSnapshotMessage",
    "HandoffSlotInfo",
    "HandoffToolCallMessage",
    "HandoffSessionEndMessage",
    "HandoffErrorMessage",
    "HandoffMessage",
    "parse_handoff_message",
]
